# Generated by Django 5.2.4 on 2025-07-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimerSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimerSequenceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timer_sequence_name", models.TextField()),
                ("started_at", models.DateTimeField(null=True)),
                (
                    "timer_sequence",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timers.timersequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimerSequenceDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("duration", models.DurationField()),
                (
                    "timer_sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timers.timersequence",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "indexes": [
                    models.Index(
                        fields=["timer_sequence", "index"],
                        name="timers_time_timer_s_741f32_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("index__gte", 0)), name="positive_index"
                    )
                ],
                "unique_together": {("timer_sequence", "index")},
            },
        ),
        migrations.CreateModel(
            name="TimerSequencePause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "timer_sequence_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timers.timersequencerun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timer_sequence_run"],
                        name="timers_time_timer_s_518ef2_idx",
                    ),
                    models.Index(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=["timer_sequence_run", "ended_at"],
                        name="pending_pause_idx",
                    ),
                ],
            },
        ),
    ]
