# Generated by Django 5.2.4 on 2025-07-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timers", "0002_timers_replace_created_by_by_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timersequenceduration",
            name="timer_sequence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="durations",
                to="timers.timersequence",
            ),
        ),
    ]
