# Generated by Django 5.2.4 on 2025-08-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0004_timers_renames_runs_in_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timersequencepause',
            name='timer_sequence_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='timers.timersequencerun'),
        ),
    ]
