# Generated by Django 5.2.4 on 2025-08-09 13:17

from django.db import migrations

from timers.models import TimerSequenceRun


update_durations_sql: str = """
UPDATE timers_timersequencerun AS run                   
SET timer_sequence_durations = dd.durations
FROM (                   
    SELECT d.timer_sequence_id, group_concat(cast (d.duration / 1000 AS int), ',') AS durations
    FROM timers_timersequenceduration d
    GROUP BY d.timer_sequence_id                   
) AS dd
WHERE run.timer_sequence_id = dd.timer_sequence_id;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("timers", "0005_alter_timersequencepause_timer_sequence_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="timersequencerun",
            name="timer_sequence_durations",
            field=TimerSequenceRun.TimerSequenceDurationsField(blank=True, null=True),
        ),
        migrations.RunSQL(update_durations_sql, reverse_sql=""),
        migrations.AlterField(
            model_name="timersequencerun",
            name="timer_sequence_durations",
            field=TimerSequenceRun.TimerSequenceDurationsField(
                blank=False, null=False, editable=False
            ),
        ),
    ]
