# Generated by Django 5.2.4 on 2025-08-09 14:28

from typing import Any
from django.utils import timezone
import django.db.models.deletion
from django.db import migrations, models
from timers.models import TimerSequenceRun, TimerSequencePause
from timers.lib.projections import TimerProjection

forward_created_by_sql = """
UPDATE timers_timersequencerun
SET created_by_id = sequence.created_by_id
FROM timers_timersequence AS sequence
WHERE sequence.id = timers_timersequencerun.timer_sequence_id
"""


def forward_ends_at(app: Any, state_editor: Any):
    now = timezone.now()
    for run in TimerSequenceRun.objects.prefetch_related("pauses").all():
        pauses = TimerSequencePause.objects.filter(timer_sequence_run=run).all()
        state = TimerProjection.from_timer_sequence_run(
            now, sequence_run=run, pauses=pauses
        )

        run.ends_at = state.ends_at
        run.save()


def backward_ends_at(app: Any, state_editor: Any):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("timers", "0006_snapshot_sequence_durations"),
    ]

    operations = [
        migrations.AddField(
            model_name="timersequencerun",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sessions.session",
                null=True,
            ),
        ),
        migrations.RunSQL(forward_created_by_sql, reverse_sql=""),
        migrations.AlterField(
            model_name="timersequencerun",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sessions.session",
                null=False,
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name="timersequencerun",
            name="ends_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.RunPython(forward_ends_at, reverse_code=backward_ends_at),
        migrations.AddIndex(
            model_name="timersequencerun",
            index=models.Index(
                fields=["ends_at"], name="timers_time_ends_at_1baf3f_idx"
            ),
        ),
    ]
