[project]
name = "django-mozza"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.0.0",
    "djlint>=1.36.4",
    "ruff>=0.12.5",
]
